config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: 'costumes#home'
  # get '/costumes/', to: 'costumes#index'
  # get '/costumes/new', to: 'costumes#new'
  # get '/costumes/:id', to: 'costumes#show', as: :costume
#   resources :costumes, only: [:index, :new, :create, :show] do
#     resources :reservations, only: :create
#   end


#   get '/users/:user_id/costumes', to: 'users#list_by_user'

#   post '/costumes/', to: 'users#create'

#   get '/costumes/:id/edit', to: 'users#edit'

#   post '/costumes/:id/edit', to: 'users#update'

#   get '/my_costumes', to: 'users#my_costumes'

#   delete '/costumes/:id', to: 'users#destroy'

#   get '/costumes/:costume_id/reservations/new', to: 'reservations#new'
#   post '/costumes/:costume_id/reservations', to: 'reservations#create'

#   get '/my_reservations/', to: 'reservations#my_reservations'
#   get '/my_requests', to: 'reservations#my_requests'
#   patch '/my_requests/:id', to: 'reservations#set_status'

resources :users do
    resources :reservations, only: [:show, :index]
end

resources :users, only: [:index, :show, :edit, :update]
resources :costumes do

    resources :reservations, only: [:new, :create]
  end

  resources :reservations, only: [:index, :show, :edit, :update]
  patch "cancel_reservation/:id", to: "reservations#cancel", as: :cancel_reservation
  patch "approved_reservation/:id", to: "reservations#approved", as: :approved_reservation
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/costume.rb
class Costume < ApplicationRecord

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  categories = %w(Corporate Animal Sports Cartoon Wedding)

  belongs_to :user
  has_many :reservations, dependent: :destroy
  validates :name, :descr, presence: true
  validates :descr, length: { minimum: 1 }
  validates :size, inclusion: { in: %w( Small Medium Large ), message: "%{ value } is not a valid size, choose small, medium or large" }
  validates :category, inclusion: { in: %w( Corporate Animal Sports Cartoon Wedding ), case_sensitive: false, message: "%{value} is not a valid category." }
  validates :price, :numericality => { greater_than: 1, message: "You're wrong! Should be greater than 1" }
  has_many_attached :images

  include PgSearch::Model
  pg_search_scope :search_by_name_and_descr,
    against: [ :name, :descr, :size, :category ],
    using: {
      tsearch: { prefix: true }
    }



  private

  def valid_category?
    categories.include? :category.downcase
  end
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :costume
  validates :status, inclusion: { in: %w(Pending Approved Rejected), default: "Pending" }
  validates :start_date, :end_date, presence: true #:type => date
  validates :user_id, :costume_id, :status,  presence: true
  validate :dates_cannot_be_in_the_past,  :end_date_is_after_start_date, on: :create


  private

  def dates_cannot_be_in_the_past
    return if end_date.blank? || start_date.blank?
    if start_date < Date.today - 1
      errors.add(:start_date, "can't be in the past!")

    elsif end_date < Date.today - 1
      errors.add(:end_date, "can't be in the past!")
    end
  end

  def end_date_is_after_start_date
    return if end_date.blank? || start_date.blank?
    if end_date < start_date
      errors.add(:end_date, "cannot be before the start date")
    end
  end



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :costumes
  has_many :reservations
  has_one_attached :profile_picture
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    include Pundit

    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :profile_picture])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile_picture])
    end
 end

app/controllers/costumes_controller.rb
class CostumesController < ApplicationController
  before_action :set_user
  before_action :set_costume, only: [:show, :edit, :update, :destroy]

  def home
    @costumes = Costume.all
  end

  def index
     if params[:query].present?
      @costumes = Costume.search_by_name_and_descr(params[:query])
    else
      @costumes = Costume.all
    end

    @markers = @costumes.geocoded.map do |costume|
      {
          lat: costume.latitude,
          lng: costume.longitude,
          info_window: render_to_string(partial: "info_window", locals: { costume: costume }),
          image_url: costume.images.first.present? ? costume.images.first.url : helpers.asset_url("unicorn.jpg")
        }
    end

  end

  def show
    @reservation = Reservation.new
    @owner = @costume.user
    @other_costumes_by_owner =  @owner.costumes - [@costume]
  end

  def new
    @costume = Costume.new
  end

  def create
    p costume_params
    @costume = Costume.new(costume_params)
    @costume.user = current_user

    # if @costume.image.nil?
    #   @costume.image = "gritty.jpg"
    # end
    if @costume.save
       redirect_to costume_path(@costume)
    else
      flash[:error] = "Some information are missing."
    end
    # no need for app/views/costumes/create.html.erb
  end

  def edit
  end

  def update
    @costume.update(costume_params)
    redirect_to costume_path(@costume)
  end

  def destroy
    # @costume = Costume.find(params[:id])
    @costume.destroy
    redirect_to costumes_path
  end

  def list_by_user
    @costumes = Costume.where(user_id: params[:user_id])
  end

  def my_costumes
    @costumes = Costume.where(user_id: params[:user_id])
  end

  private

  def set_costume
    @costume = Costume.find(params[:id])
  end

  def costume_params

    params.require(:costume).permit(:name, :descr, :price, :size, :category, :user_id, :address, images: [])

  end

  def set_user
    @user = current_user
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :find_reservation, only: [:show, :edit, :update, :cancel, :approved]
  before_action :find_user
  before_action :find_costume, only: [:new, :create]

def index
   @my_reservations = Reservation.where(user_id:current_user).where.not(status:"Rejected")
    my_costume_ids = Costume.where(user_id:current_user).pluck(:id)
    @my_requests = []

   my_costume_ids.each do |id|
      matching_results =  Reservation.where(costume_id:id).where.not(status:"Rejected")
      matching_results.each do |result|
        @my_requests << result
      end
   end
   ##Following variables are a count of reservation/requests belonging to the user where the status is not Rejected
  #  @my_reservation_count = Reservation.where(user_id:current_user).where.not(status:"Rejected").count
  #  @my_requests_count = @my_requests.where.not(status:"Rejected").count


end
def show; end
def new
    @reservation = Reservation.new
end

def create
    @owner = @costume.user
    @other_costumes_by_owner = @owner.costumes - [@costume]
    @reservation = Reservation.new(reservation_params)
    @reservation.user = current_user
    @reservation.costume = @costume
    @reservation.status = "Pending"
    if @reservation.save
      redirect_to user_reservations_path(@user)
    else
      render 'costumes/show'
    end
end
def edit; end
def update
    @reservation.update(reservation_params)
    redirect_to reservations_path
end

def cancel
    @reservation.status = "Rejected"
    @reservation.save!
    redirect_to reservations_path(anchor: "profile-tab")
end
def approved
    @reservation.status = "Approved"
    @reservation.save!
    redirect_to reservations_path(anchor: "profile-tab")
end

private
def reservation_params
    params.require(:reservation).permit(:status, :start_date, :end_date)
end
def find_user
    @user = current_user
end
def find_reservation
    @reservation = Reservation.find(params[:id])
end

def find_costume
  @costume = Costume.find(params[:costume_id])
end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
      #No code needed here, just a placeholder for the 'Get' action
    end

    def create
    end

    def destroy
      session.clear
      @_current_user = nil
      redirect_to '/'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/costumes/_banner.html.erb
  <div class="banner">
    <div class=" text-center d-flex justify-content-center align-items-center">
      <div class="p-2">
        <%= image_tag "colors.jpg", class:" radius border border-light" %>
      </div>
      <div class="color-frame d-flex flex-column justify-content-around p-2">
        <div class="d-flex flex-column justify-content-center">
          <h1> Mascot BnB  </h1>
          <h3> Rent the most <strong>fun </strong> and <strong>original</strong> <br>mascot costumes !</h3>
        </div>
        <%= link_to "Find your costume", costumes_path, class: "text-decoration-none btn-gray p-3" %>
      </div>
      <div class="p-2">
        <%= image_tag "colors green.jpg", class:"radius border border-light " %>
      </div>
    </div>
  </div>

app/views/costumes/_card.html.erb
<div class="costume-card">

    <div class="costume-card__cover-photo pt-2" style="text-align: center;">
<% costume.images.take(1).each do |image| %>
            <%= cl_image_tag image.key, width: 320, height: 180, crop: :fit%>
            <% end %>

      </div>

  <div class="costume-card__avatar" style="background-image: url('<%= cl_image_path costume.user.profile_picture.key %>');"></div>

  <%# <% favourite = costume.favourites.to_a.find { |fav| fav.user == current_user} %>



  <div class="costume-card__body">
    <%= link_to costume_path(costume), class: "text-decoration-none" do %>
      <h2 class="costume-card__title font-text font-colour-charcoal font-weight-regular font-size-18"><%= costume.name %></h2>
    <% end %>

    <div class="costume-card__lower">
      <p class="costume-card__date font-text font-colour-light-grey font-size-12">Montreal | <%= costume.created_at.strftime("%b %e, %Y") %></p>

      <% if costume.price == 0 %>
        <p class="costume-card__price font-text font-colour-charcoal font-weight-medium font-size-18"><strong>FREE</strong></p>
      <% else %>
        <p class="costume-card__price font-text font-colour-charcoal font-weight-medium font-size-18"><strong><%= number_to_currency costume.price %></strong></p>
      <% end %>
    </div>
  </div>
</div>

app/views/costumes/_info_window.html.erb
<div><h4><%= link_to costume.name, costume_path(costume), class: "map-costume-name" %></h4></div>
<p><%= costume.address %></p>
<%if costume.images.present?%>
<p><%= cl_image_tag costume.images.first.key, height: 80, width:80, crop: :fill  %></p>
<% end %>

app/views/costumes/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-6 mt-3 p-3 bg-light">
      <h1>Update the costume:</h1>
      <%= simple_form_for  @costume do |f| %>
      <%= f.input :name %>
      <%= f.input :descr %>
      <%= f.input :address,
              wrapper_html: { data: { controller: "geocoder", geocoder_api_key_value: ENV['MAPBOX_API_KEY'] } } %>
      <%= f.input :price %>
      <%= f.input :size, :collection => %w[Small Medium Large] %>
      <%= f.input :category, :collection => %w[Corporate Animal Sports Cartoon Wedding]%>
      <%= f.input :images, as: :file, input_html: { multiple: true} %>
      <%= f.submit 'Update the changes', class:"btn-gray" %>
    <% end %>
    </div>
  </div>
</div>

app/views/costumes/home.html.erb
 <%= render "banner" %>
<div class="container ">
  <div class="row text-light">
  <h2>New arrivals</h2>
    <div class="cards">
      <% @costumes.last(4).each do |costume| %>
      <%= link_to costume_path(costume), class: "text-decoration-none" do %>
      <div class="card-trip p-3 ">
        <% costume.images.take(1).each do |image| %>
          <%= cl_image_tag image.key, :transformation=>[
            { :dpr => "auto", :responsive => true, :width => "auto", :crop => "scale"},
            {:height=>300, :crop=>"scale"}
            ] %>
         <% end %>
            <div class="card-trip-infos">
              <div>
                <h2><%= costume.name %></h2>
                <p> <%= costume.descr %></p>
              </div>
              <h2 class="card-trip-pricing"><%= costume.price %>$</h2>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/costumes/index.html.erb
<div class="map-index"
  data-controller="mapbox"
  data-mapbox-markers-value="<%= @markers.to_json %>"
  data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

<div class="container">
  <div class="row">
    <div class="mt-6">
        <div class="d-flex align-items-center justify-content-center mt-2">
          <div class="flex-grow-1">
            <%= form_tag costumes_path, method: :get do %>
            <%= text_field_tag :query,
              params[:query],
              class: "form-control",
              placeholder: "Find a costume"
            %>
          </div class="my-3">
            <%= submit_tag "Search", class: "btn-gray mx-3" %>
          </div>
      <% end %>
      <div class="cards my-5">
        <% @costumes.each do |costume| %>
        <%= link_to costume_path(costume), class: "text-decoration-none" do %>
          <div class="card-trip p-3">
            <div class="mb-3 text-center">
              <h2><%= costume.name.capitalize %></h2>
            </div>
            <% costume.images.take(1).each do |image| %>
            <%= cl_image_tag image.key, :transformation=>[
            { :dpr => "auto", :responsive => true, :width => "auto", :crop => "scale"},
            {:height=>300, :crop=>"scale"}
            ] %>
            <% end %>
            <div class="card-trip-infos d-flex justify-content-between p-3">
              <p> <%= costume.descr %></p>
              <p class="card-trip-pricing">$<%= costume.price %></p>
              <%# <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" /> %>
            </div>
          </div>
          <% end %>
        <% end %>
      </div>
     </div>
  </div>
</div>

app/views/costumes/new.html.erb
<div class="container w-50 mw-100">
  <div class="row">
    <div class="col-9 ">
      <div class="form">
          <%= simple_form_for @costume  do |f| %>
            <%= f.input :name, :label => 'Name' %>
            <%= f.input :descr, :label => 'Description', :hint => 'Hint: write an original description, to stand out' %>
            <%= f.input :address, :label => 'Address',
                    input_html: { data: { geocoder_target: "address" }, class: 'd-none'},
                    wrapper_html: { data: { controller: "geocoder", geocoder_api_key_value: ENV['MAPBOX_API_KEY'] } } %>
            <%= f.input :price, :label => 'Price per Day'%>
            <%= f.input :size, :collection => %w[Small Medium Large],:label => 'Select a Size'  %>
            <%= f.input :category, :collection => %w[Corporate Animal Sports Cartoon Wedding],:label => 'Select a Category'%>
            <%= f.input :images, as: :file, input_html: { multiple: true}, :hint => 'Hint: Good quality pictures attract greater attention' %>
            <%= f.submit 'Add', id: "#myModal", class:"btn-orange", data: { toggle:"modal", target:"#myModal"}  %>
          <% end %>
            <!-- Modal HTML -->
            <div id="myModal" class="modal fade">
              <div class="modal-dialog modal-confirm">
                <div class="modal-content">
                  <div class="modal-header justify-content-center">
                    <div class="icon-box">
                      <i class="material-icons">&#xE876;</i>
                    </div>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                  </div>
                  <div class="modal-body text-center">
                    <h4>Success!</h4>
                    <p>You've successfully added a costume.</p>
                  </div>
                </div>
              </div>
            </div>
      </div>
    </div>
  </div>
</div>

app/views/costumes/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="my-4 d-flex justify-content-start">
        <h6>
          <%= link_to costumes_path, class: "text-decoration-none text-primary" do %>
          <i class="fa-solid fa-angle-left"></i> Back
          <% end %>
        </h6>
        <% if current_user == @owner  && user_signed_in? && @owner.name == current_user.name %>
          <div class="d-flex justify-content-end">
            <%= link_to edit_costume_path(@costume),class: "px-3 text-primary" do %>
              <i class="fa-solid fa-pen-to-square"></i>
              Edit
            <% end %>
            <%= link_to costume_path(@costume), class: "text-danger", method: :delete,
                        data: {confirm: 'Are you sure?'} do %>
                <i class="fa-solid fa-trash-can"></i>
                Delete
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row d-flex justify-content-around">
    <div class="col-6 mt-6">
      <div class="card-trip p-3">
        <h4 class="text-center"> <%= @costume.name.capitalize %></h4>
          <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner d-flex justify-content-around ">
            <% @costume.images.each do |image| %>
               <% if image == @costume.images.first %>
                  <div class="carousel-item active">
                    <%= cl_image_tag image.key,  :transformation=>[
                                                { :dpr => "auto", :responsive => true, :crop => "scale",
                                                :height=>300, :crop=>"scale"}
                                                ]
                    %>
                  </div>
                <%else%>
                  <div class="carousel-item">
                    <%= cl_image_tag image.key, :transformation=>[
                                                { :dpr => "auto", :responsive => true, :crop => "scale",
                                                :height=>300, :crop=>"scale"}
                                                ] %>
                  </div>
                <%end%>
            <%end%>
          </div>
        </div>
      <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
      <div class="card-trip-infos d-flex flex-column ">
        <h5 class="p-2 text-warning"> <em><%= @costume.descr %></em></h5>
        <div class="p-2 d-flex justify-content-between align-items-start">
          <div class="d-flex flex-column justify-content-between">
            <h6 class="text-warning"> Category: <%= @costume.category %></h6>
            <h6 class="text-primary"> Owner: <%= @owner.name %></h6>
          </div>
          <div class="d-flex flex-column justify-content-between">
            <h6 class="text-success"> Size: <%= @costume.size %> </h6>
            <h5 class="text-success"> $ <%= @costume.price %> </h5>
          </div>
        </div>
      </div>
    </div>
  </div>
    <% if current_user != @owner  && user_signed_in? %>
      <div class="col-6">
          <%= simple_form_for [@costume, @reservation] do |f| %>
          <h4>Reserve me!</h4>
          <%= f.input :start_date, as: :date , html5: true %>
          <%= f.input :end_date, as: :date, html5: true%>
          <%= f.submit "Reserve", class: "btn-orange" %>
          <% end %>
      </div>
    <% end %>
  </div>
  <br>
  <div class="container mb-5">
  <div class="row text-light">
      <% if @other_costumes_by_owner.size > 0 && current_user != @owner %>
         <h2 style="text-align: center">Other costumes from <%= @owner.name %> </h2>
      <% else %>
            <% if @other_costumes_by_owner.size > 0%>
              <h2 style="text-align: center">Other costumes from my collection </h2>
              <% else %>
              <h2 style="text-align: center">No other costumes from collection <%= link_to "Add New Costume To My Collection", new_costume_path, class:"nav-link p-1 ms-5" %></h2>
              <% end %>
      <% end %>
        <div class="cards">
        <% @other_costumes_by_owner.each do |costume| %>
              <%= link_to costume_path(costume), class: "text-decoration-none" do %>
        <div class="card-trip p-3 ">
          <% costume.images.take(1).each do |image| %>
            <%= cl_image_tag image.key, :transformation=>[
              { :dpr => "auto", :responsive => true, :width => "auto", :crop => "scale"},
              {:height=>300, :crop=>"scale"}
              ] %>
          <% end %>
          <div class="card-trip-infos">
            <div>
              <h2><%= costume.name %></h2>
              <p> <%= costume.descr %></p>
            </div>
            <h2 class="card-trip-pricing"><%= costume.price %>$</h2>
          </div>
        </div>
        <% end %>
        <% end %>
      </div>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MascotCostumesAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
  </head>

  <body>
    <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/reservations/edit.html.erb
<h2>Change a rental:</h2>
<%= simple_form_for [@costume, @reservation] do |f|, remote: true %>
  <%= f.input :start_date, as: :date %>
  <%= f.input :end_date, as: :date %>
  <%= f.submit "Edit rental", class: "btn-orange" %>
<% end %>

app/views/reservations/index.html.erb
<div class="container border border-warning">
  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" id="home-tab" data-toggle="pill" href="#home" role="tab" aria-controls="home" aria-selected="true">My Reservations (<%= @my_reservations.size %>)</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="profile-tab" data-toggle="pill" href="#profile" role="tab" aria-controls="profile" aria-selected="false">My Requests (<%= @my_requests.size %>)</a>
    </li>
  </ul>
  <div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
        <br>
              <table style="table-layout: fixed; width: 100%;" class="chart">
                <tr>
                  <th>Costume Name</th>
                  <th>Start Date</th>
                  <th>End Date</th>
                  <th>Owner</th>
                  <th>Status</th>
                </tr>
              <% @my_reservations.each do |r| %>
                    <tr>
                      <td class="nr"><%= r.costume.name %></td>
                      <td><%= r.start_date %></td>
                      <td><%= r.end_date %></td>
                      <td><%= r.costume.user.name %></td>
                      <td><%= r.status %></td>
                      <td><%= link_to "Cancel", cancel_reservation_path(r), method: :patch,
                              data: {confirm: 'Are you sure?'}, class: "btn-orange", remote: true %></td>
                    </tr>
                <% end %>
              </table>
    </div>
    <div class="tab-pane fade" id="profile" role="tabpanel"  aria-labelledby="profile-tab">
        <br>
        <table style="table-layout: fixed; width: 100%;"  class="chart">
        <tr>
          <th>Costume Name</th>
          <th>Start Date</th>
          <th>End Date</th>
          <th>Requested By</th>
          <th>Status</th>
        </tr>
        <% @my_requests.each do |r| %>
            <tr>
              <td class="nr"><%= r.costume.name %></td>
              <td><%= r.start_date %></td>
              <td><%= r.end_date %></td>
              <td><%= r.user.name %></td>
              <td><%= r.status %></td>
              <td><%= link_to "Reject", cancel_reservation_path(r), method: :patch, remote: true,
                      data: {confirm: 'Are you sure?'}, class: "btn-gray" %></td>
              <td><%= link_to "Approve this rental", approved_reservation_path(r), method: :patch, remote: true,
                      data: {confirm: 'Are you sure?'}, class: "btn-gray" %></td>
            </tr>
          <% end %>
        </table>
    </div>
  </div>
</div>

<script>
    $(document).ready(function ($) {
        let openTab = window.location.hash;
        $(openTab).trigger('click');
    })
</script>

app/views/reservations/new.html.erb
<h2 style="text-align: center;">Create a Rental</h2>
  <div class="form">
  <%= simple_form_for [@costume, @reservation] do |f|, remote: true %>
    <div class="form-content">
      <div class="left-form">
        <%# <% picture = "" %>
        <%= image_tag picture, class:"image-left-form", alt:@costume.name%>
      </div>
      <div class="right-form">
        <div class="start-date">
          <%= f.input :start_date, as: :date %>
        </div>
        <div class="end-date">
          <%= f.input :end_date, as: :date %>
        </div>
      </div>
    </div>
    <%= f.submit "Create rental", class:"btn btn-grad submit" %>
  <% end %>
</div>

app/views/reservations/show.html.erb
<h1><%= @costume.name %></h1>
<h3>Descr: <%= @costume.descr %> / Size: <%= @costume.size %></h3>
<p>Price: <%= @costume.price %> / Category: <%= @costume.category %></p>
<%# <img src=<%= @costume.picture %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-text">
    Made by Andrii, J-f, Suzanne and Mark
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path do %>
    <%= image_tag "chinese costume.jpg", class: 'logo' %>
    <% end %>

  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
   </button>
   <% if user_signed_in? %>
      <li class="greeting">Welcome, <strong><%= current_user.name.upcase %></strong></li>
   <% end %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Add Costume", new_costume_path, class:"nav-link p-1 ms-5" %>
        </li>
        <li class="nav-item">
          <%= link_to "My Rentals", user_reservations_path(@user), class:"nav-link p-1 ms-5" %>
        </li>


        <li class="nav-item">
          <% if current_page?(root_path)%>
            <%= link_to "Browse all Costumes", costumes_path, class:"nav-link underline p-1 ms-5"  %>
          <% else %>
            <%= link_to "Browse all Costumes", costumes_path, class:"nav-link p-1 ms-5" %>
          <% end %>
        </li>

          <li>
            <%= link_to "Sign out", destroy_user_session_path, method: :delete, class:"nav-link p-1 ms-5"  %>
          </li>
        <% else %>
          <li>
            <%= link_to "Login", user_session_path, class:"nav-link p-1 ms-5" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>